spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/db_khpl_uzikbbang
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                "[format_sql]": true

uzik:
    auth-key: 'VW3XWmnGj7Jul1fek8cN2fX8awaTtjvbHF70b461N5o='